<?php

declare(strict_types=1);

namespace ProductTrap\Enums;

enum Currency: string
{
    case ALL = 'ALL';
    case AFN = 'AFN';
    case ARS = 'ARS';
    case AWG = 'AWG';
    case AUD = 'AUD';
    case AZN = 'AZN';
    case BSD = 'BSD';
    case BBD = 'BBD';
    case BYR = 'BYR';
    case BZD = 'BZD';
    case BMD = 'BMD';
    case BOB = 'BOB';
    case BAM = 'BAM';
    case BWP = 'BWP';
    case BGN = 'BGN';
    case BRL = 'BRL';
    case BND = 'BND';
    case KHR = 'KHR';
    case CAD = 'CAD';
    case KYD = 'KYD';
    case CLP = 'CLP';
    case CNY = 'CNY';
    case COP = 'COP';
    case CRC = 'CRC';
    case HRK = 'HRK';
    case CUP = 'CUP';
    case CZK = 'CZK';
    case DKK = 'DKK';
    case DOP = 'DOP';
    case EGP = 'EGP';
    case SVC = 'SVC';
    case EEK = 'EEK';
    case EUR = 'EUR';
    case FKP = 'FKP';
    case FJD = 'FJD';
    case GEL = 'GEL';
    case GHC = 'GHC';
    case GIP = 'GIP';
    case GTQ = 'GTQ';
    case GGP = 'GGP';
    case GYD = 'GYD';
    case HNL = 'HNL';
    case HKD = 'HKD';
    case HUF = 'HUF';
    case ISK = 'ISK';
    case INR = 'INR';
    case IDR = 'IDR';
    case IRR = 'IRR';
    case IMP = 'IMP';
    case ILS = 'ILS';
    case JMD = 'JMD';
    case JPY = 'JPY';
    case JEP = 'JEP';
    case KZT = 'KZT';
    case KPW = 'KPW';
    case KRW = 'KRW';
    case KGS = 'KGS';
    case LAK = 'LAK';
    case LVL = 'LVL';
    case LBP = 'LBP';
    case LRD = 'LRD';
    case LTL = 'LTL';
    case MKD = 'MKD';
    case MYR = 'MYR';
    case MUR = 'MUR';
    case MXN = 'MXN';
    case MNT = 'MNT';
    case MZN = 'MZN';
    case NAD = 'NAD';
    case NPR = 'NPR';
    case ANG = 'ANG';
    case NZD = 'NZD';
    case NIO = 'NIO';
    case NGN = 'NGN';
    case NOK = 'NOK';
    case OMR = 'OMR';
    case PKR = 'PKR';
    case PAB = 'PAB';
    case PYG = 'PYG';
    case PEN = 'PEN';
    case PHP = 'PHP';
    case PLN = 'PLN';
    case QAR = 'QAR';
    case RON = 'RON';
    case RUB = 'RUB';
    case SHP = 'SHP';
    case SAR = 'SAR';
    case RSD = 'RSD';
    case SCR = 'SCR';
    case SGD = 'SGD';
    case SBD = 'SBD';
    case SOS = 'SOS';
    case ZAR = 'ZAR';
    case LKR = 'LKR';
    case SEK = 'SEK';
    case CHF = 'CHF';
    case SRD = 'SRD';
    case SYP = 'SYP';
    case TWD = 'TWD';
    case THB = 'THB';
    case TTD = 'TTD';
    case TRL = 'TRL';
    case TVD = 'TVD';
    case UAH = 'UAH';
    case GBP = 'GBP';
    case USD = 'USD';
    case UYU = 'UYU';
    case UZS = 'UZS';
    case VEF = 'VEF';
    case VND = 'VND';
    case YER = 'YER';
    case ZWD = 'ZWD';

    public function symbol(): string
    {
        return match ($this) {
            static::ALL => 'Lek',
            static::AFN => '؋',
            static::ARS => '$',
            static::AWG => 'ƒ',
            static::AUD => '$',
            static::AZN => '₼',
            static::BSD => '$',
            static::BBD => '$',
            static::BYR => 'p.',
            static::BZD => 'BZ$',
            static::BMD => '$',
            static::BOB => '$b',
            static::BAM => 'KM',
            static::BWP => 'P',
            static::BGN => 'лв',
            static::BRL => 'R$',
            static::BND => '$',
            static::KHR => '៛',
            static::CAD => '$',
            static::KYD => '$',
            static::CLP => '$',
            static::CNY => '¥',
            static::COP => '$',
            static::CRC => '₡',
            static::HRK => 'kn',
            static::CUP => '₱',
            static::CZK => 'Kč',
            static::DKK => 'kr',
            static::DOP => 'RD$',
            static::EGP => '£',
            static::SVC => '$',
            static::EEK => 'kr',
            static::EUR => '€',
            static::FKP => '£',
            static::FJD => '$',
            static::GEL => '₾',
            static::GHC => '¢',
            static::GIP => '£',
            static::GTQ => 'Q',
            static::GGP => '£',
            static::GYD => '$',
            static::HNL => 'L',
            static::HKD => '$',
            static::HUF => 'Ft',
            static::ISK => 'kr',
            static::INR => '₹',
            static::IDR => 'Rp',
            static::IRR => '﷼',
            static::IMP => '£',
            static::ILS => '₪',
            static::JMD => 'J$',
            static::JPY => '¥',
            static::JEP => '£',
            static::KZT => 'лв',
            static::KPW => '₩',
            static::KRW => '₩',
            static::KGS => 'лв',
            static::LAK => '₭',
            static::LVL => 'Ls',
            static::LBP => '£',
            static::LRD => '$',
            static::LTL => 'Lt',
            static::MKD => 'ден',
            static::MYR => 'RM',
            static::MUR => '₨',
            static::MXN => '$',
            static::MNT => '₮',
            static::MZN => 'MT',
            static::NAD => '$',
            static::NPR => '₨',
            static::ANG => 'ƒ',
            static::NZD => '$',
            static::NIO => 'C$',
            static::NGN => '₦',
            static::NOK => 'kr',
            static::OMR => '﷼',
            static::PKR => '₨',
            static::PAB => 'B/.',
            static::PYG => 'Gs',
            static::PEN => 'S/.',
            static::PHP => '₱',
            static::PLN => 'zł',
            static::QAR => '﷼',
            static::RON => 'lei',
            static::RUB => '₽',
            static::SHP => '£',
            static::SAR => '﷼',
            static::RSD => 'Дин.',
            static::SCR => '₨',
            static::SGD => '$',
            static::SBD => '$',
            static::SOS => 'S',
            static::ZAR => 'R',
            static::LKR => '₨',
            static::SEK => 'kr',
            static::CHF => 'CHF',
            static::SRD => '$',
            static::SYP => '£',
            static::TWD => 'NT$',
            static::THB => '฿',
            static::TTD => 'TT$',
            static::TRL => '₺',
            static::TVD => '$',
            static::UAH => '₴',
            static::GBP => '£',
            static::USD => '$',
            static::UYU => '$U',
            static::UZS => 'лв',
            static::VEF => 'Bs',
            static::VND => '₫',
            static::YER => '﷼',
            static::ZWD => 'Z$',
        };
    }
}
