<?php

declare(strict_types=1);

namespace ProductTrap\Enums;

enum Currency: string
{
    case ALL = 'ALL';
    case AFN = 'AFN';
    case ARS = 'ARS';
    case AWG = 'AWG';
    case AUD = 'AUD';
    case AZN = 'AZN';
    case BSD = 'BSD';
    case BBD = 'BBD';
    case BYR = 'BYR';
    case BZD = 'BZD';
    case BMD = 'BMD';
    case BOB = 'BOB';
    case BAM = 'BAM';
    case BWP = 'BWP';
    case BGN = 'BGN';
    case BRL = 'BRL';
    case BND = 'BND';
    case KHR = 'KHR';
    case CAD = 'CAD';
    case KYD = 'KYD';
    case CLP = 'CLP';
    case CNY = 'CNY';
    case COP = 'COP';
    case CRC = 'CRC';
    case HRK = 'HRK';
    case CUP = 'CUP';
    case CZK = 'CZK';
    case DKK = 'DKK';
    case DOP = 'DOP';
    case EGP = 'EGP';
    case SVC = 'SVC';
    case EEK = 'EEK';
    case EUR = 'EUR';
    case FKP = 'FKP';
    case FJD = 'FJD';
    case GEL = 'GEL';
    case GHC = 'GHC';
    case GIP = 'GIP';
    case GTQ = 'GTQ';
    case GGP = 'GGP';
    case GYD = 'GYD';
    case HNL = 'HNL';
    case HKD = 'HKD';
    case HUF = 'HUF';
    case ISK = 'ISK';
    case INR = 'INR';
    case IDR = 'IDR';
    case IRR = 'IRR';
    case IMP = 'IMP';
    case ILS = 'ILS';
    case JMD = 'JMD';
    case JPY = 'JPY';
    case JEP = 'JEP';
    case KZT = 'KZT';
    case KPW = 'KPW';
    case KRW = 'KRW';
    case KGS = 'KGS';
    case LAK = 'LAK';
    case LVL = 'LVL';
    case LBP = 'LBP';
    case LRD = 'LRD';
    case LTL = 'LTL';
    case MKD = 'MKD';
    case MYR = 'MYR';
    case MUR = 'MUR';
    case MXN = 'MXN';
    case MNT = 'MNT';
    case MZN = 'MZN';
    case NAD = 'NAD';
    case NPR = 'NPR';
    case ANG = 'ANG';
    case NZD = 'NZD';
    case NIO = 'NIO';
    case NGN = 'NGN';
    case NOK = 'NOK';
    case OMR = 'OMR';
    case PKR = 'PKR';
    case PAB = 'PAB';
    case PYG = 'PYG';
    case PEN = 'PEN';
    case PHP = 'PHP';
    case PLN = 'PLN';
    case QAR = 'QAR';
    case RON = 'RON';
    case RUB = 'RUB';
    case SHP = 'SHP';
    case SAR = 'SAR';
    case RSD = 'RSD';
    case SCR = 'SCR';
    case SGD = 'SGD';
    case SBD = 'SBD';
    case SOS = 'SOS';
    case ZAR = 'ZAR';
    case LKR = 'LKR';
    case SEK = 'SEK';
    case CHF = 'CHF';
    case SRD = 'SRD';
    case SYP = 'SYP';
    case TWD = 'TWD';
    case THB = 'THB';
    case TTD = 'TTD';
    case TRL = 'TRL';
    case TVD = 'TVD';
    case UAH = 'UAH';
    case GBP = 'GBP';
    case USD = 'USD';
    case UYU = 'UYU';
    case UZS = 'UZS';
    case VEF = 'VEF';
    case VND = 'VND';
    case YER = 'YER';
    case ZWD = 'ZWD';

    public function symbol(): string
    {
        return match ($this) {
            self::ALL => 'Lek',
            self::AFN => '؋',
            self::ARS, self::USD, self::AUD, self::BSD, self::BBD, self::BMD, self::CAD, self::KYD, self::CLP, self::BND, self::COP, self::SVC, self::FJD, self::GYD, self::HKD, self::LRD, self::MXN, self::NAD, self::NZD, self::SGD, self::SBD, self::SRD, self::TVD => '$',
            self::AWG, self::ANG => 'ƒ',
            self::AZN => '₼',
            self::BYR => 'p.',
            self::BZD => 'BZ$',
            self::BOB => '$b',
            self::BAM => 'KM',
            self::BWP => 'P',
            self::BGN, self::UZS, self::KZT, self::KGS => 'лв',
            self::BRL => 'R$',
            self::KHR => '៛',
            self::CNY, self::JPY => '¥',
            self::CRC => '₡',
            self::HRK => 'kn',
            self::CUP, self::PHP => '₱',
            self::CZK => 'Kč',
            self::DKK, self::EEK, self::ISK, self::NOK, self::SEK => 'kr',
            self::DOP => 'RD$',
            self::EGP, self::FKP, self::GIP, self::GGP, self::IMP, self::JEP, self::LBP, self::SHP, self::SYP, self::GBP => '£',
            self::EUR => '€',
            self::GEL => '₾',
            self::GHC => '¢',
            self::GTQ => 'Q',
            self::HNL => 'L',
            self::HUF => 'Ft',
            self::INR => '₹',
            self::IDR => 'Rp',
            self::IRR, self::YER, self::OMR, self::QAR, self::SAR => '﷼',
            self::ILS => '₪',
            self::JMD => 'J$',
            self::KPW, self::KRW => '₩',
            self::LAK => '₭',
            self::LVL => 'Ls',
            self::LTL => 'Lt',
            self::MKD => 'ден',
            self::MYR => 'RM',
            self::MUR, self::NPR, self::PKR, self::SCR, self::LKR => '₨',
            self::MNT => '₮',
            self::MZN => 'MT',
            self::NIO => 'C$',
            self::NGN => '₦',
            self::PAB => 'B/.',
            self::PYG => 'Gs',
            self::PEN => 'S/.',
            self::PLN => 'zł',
            self::RON => 'lei',
            self::RUB => '₽',
            self::RSD => 'Дин.',
            self::SOS => 'S',
            self::ZAR => 'R',
            self::CHF => 'CHF',
            self::TWD => 'NT$',
            self::THB => '฿',
            self::TTD => 'TT$',
            self::TRL => '₺',
            self::UAH => '₴',
            self::UYU => '$U',
            self::VEF => 'Bs',
            self::VND => '₫',
            self::ZWD => 'Z$',
        };
    }
}
