<?php

declare(strict_types=1);

namespace ProductTrap\Enums;

enum Currency: string
{
    case ALL = 'ALL';
    case AFN = 'AFN';
    case ARS = 'ARS';
    case AWG = 'AWG';
    case AUD = 'AUD';
    case AZN = 'AZN';
    case BSD = 'BSD';
    case BBD = 'BBD';
    case BYR = 'BYR';
    case BZD = 'BZD';
    case BMD = 'BMD';
    case BOB = 'BOB';
    case BAM = 'BAM';
    case BWP = 'BWP';
    case BGN = 'BGN';
    case BRL = 'BRL';
    case BND = 'BND';
    case KHR = 'KHR';
    case CAD = 'CAD';
    case KYD = 'KYD';
    case CLP = 'CLP';
    case CNY = 'CNY';
    case COP = 'COP';
    case CRC = 'CRC';
    case HRK = 'HRK';
    case CUP = 'CUP';
    case CZK = 'CZK';
    case DKK = 'DKK';
    case DOP = 'DOP';
    case EGP = 'EGP';
    case SVC = 'SVC';
    case EEK = 'EEK';
    case EUR = 'EUR';
    case FKP = 'FKP';
    case FJD = 'FJD';
    case GEL = 'GEL';
    case GHC = 'GHC';
    case GIP = 'GIP';
    case GTQ = 'GTQ';
    case GGP = 'GGP';
    case GYD = 'GYD';
    case HNL = 'HNL';
    case HKD = 'HKD';
    case HUF = 'HUF';
    case ISK = 'ISK';
    case INR = 'INR';
    case IDR = 'IDR';
    case IRR = 'IRR';
    case IMP = 'IMP';
    case ILS = 'ILS';
    case JMD = 'JMD';
    case JPY = 'JPY';
    case JEP = 'JEP';
    case KZT = 'KZT';
    case KPW = 'KPW';
    case KRW = 'KRW';
    case KGS = 'KGS';
    case LAK = 'LAK';
    case LVL = 'LVL';
    case LBP = 'LBP';
    case LRD = 'LRD';
    case LTL = 'LTL';
    case MKD = 'MKD';
    case MYR = 'MYR';
    case MUR = 'MUR';
    case MXN = 'MXN';
    case MNT = 'MNT';
    case MZN = 'MZN';
    case NAD = 'NAD';
    case NPR = 'NPR';
    case ANG = 'ANG';
    case NZD = 'NZD';
    case NIO = 'NIO';
    case NGN = 'NGN';
    case NOK = 'NOK';
    case OMR = 'OMR';
    case PKR = 'PKR';
    case PAB = 'PAB';
    case PYG = 'PYG';
    case PEN = 'PEN';
    case PHP = 'PHP';
    case PLN = 'PLN';
    case QAR = 'QAR';
    case RON = 'RON';
    case RUB = 'RUB';
    case SHP = 'SHP';
    case SAR = 'SAR';
    case RSD = 'RSD';
    case SCR = 'SCR';
    case SGD = 'SGD';
    case SBD = 'SBD';
    case SOS = 'SOS';
    case ZAR = 'ZAR';
    case LKR = 'LKR';
    case SEK = 'SEK';
    case CHF = 'CHF';
    case SRD = 'SRD';
    case SYP = 'SYP';
    case TWD = 'TWD';
    case THB = 'THB';
    case TTD = 'TTD';
    case TRL = 'TRL';
    case TVD = 'TVD';
    case UAH = 'UAH';
    case GBP = 'GBP';
    case USD = 'USD';
    case UYU = 'UYU';
    case UZS = 'UZS';
    case VEF = 'VEF';
    case VND = 'VND';
    case YER = 'YER';
    case ZWD = 'ZWD';


    public function symbol(): string
    {
        return match ($this) {
            'ALL' => "Lek",
            'AFN' => "؋",
            'ARS' => "$",
            'AWG' => "ƒ",
            'AUD' => "$",
            'AZN' => "₼",
            'BSD' => "$",
            'BBD' => "$",
            'BYR' => "p.",
            'BZD' => "BZ$",
            'BMD' => "$",
            'BOB' => "\$b",
            'BAM' => "KM",
            'BWP' => "P",
            'BGN' => "лв",
            'BRL' => "R$",
            'BND' => "$",
            'KHR' => "៛",
            'CAD' => "$",
            'KYD' => "$",
            'CLP' => "$",
            'CNY' => "¥",
            'COP' => "$",
            'CRC' => "₡",
            'HRK' => "kn",
            'CUP' => "₱",
            'CZK' => "Kč",
            'DKK' => "kr",
            'DOP' => "RD$",
            'EGP' => "£",
            'SVC' => "$",
            'EEK' => "kr",
            'EUR' => "€",
            'FKP' => "£",
            'FJD' => "$",
            'GEL' => "₾",
            'GHC' => "¢",
            'GIP' => "£",
            'GTQ' => "Q",
            'GGP' => "£",
            'GYD' => "$",
            'HNL' => "L",
            'HKD' => "$",
            'HUF' => "Ft",
            'ISK' => "kr",
            'INR' => "₹",
            'IDR' => "Rp",
            'IRR' => "﷼",
            'IMP' => "£",
            'ILS' => "₪",
            'JMD' => "J$",
            'JPY' => "¥",
            'JEP' => "£",
            'KZT' => "лв",
            'KPW' => "₩",
            'KRW' => "₩",
            'KGS' => "лв",
            'LAK' => "₭",
            'LVL' => "Ls",
            'LBP' => "£",
            'LRD' => "$",
            'LTL' => "Lt",
            'MKD' => "ден",
            'MYR' => "RM",
            'MUR' => "₨",
            'MXN' => "$",
            'MNT' => "₮",
            'MZN' => "MT",
            'NAD' => "$",
            'NPR' => "₨",
            'ANG' => "ƒ",
            'NZD' => "$",
            'NIO' => "C$",
            'NGN' => "₦",
            'NOK' => "kr",
            'OMR' => "﷼",
            'PKR' => "₨",
            'PAB' => "B/.",
            'PYG' => "Gs",
            'PEN' => "S/.",
            'PHP' => "₱",
            'PLN' => "zł",
            'QAR' => "﷼",
            'RON' => "lei",
            'RUB' => "₽",
            'SHP' => "£",
            'SAR' => "﷼",
            'RSD' => "Дин.",
            'SCR' => "₨",
            'SGD' => "$",
            'SBD' => "$",
            'SOS' => "S",
            'ZAR' => "R",
            'LKR' => "₨",
            'SEK' => "kr",
            'CHF' => "CHF",
            'SRD' => "$",
            'SYP' => "£",
            'TWD' => "NT$",
            'THB' => "฿",
            'TTD' => "TT$",
            'TRL' => "₺",
            'TVD' => "$",
            'UAH' => "₴",
            'GBP' => "£",
            'USD' => "$",
            'UYU' => "\$U",
            'UZS' => "лв",
            'VEF' => "Bs",
            'VND' => "₫",
            'YER' => "﷼",
            'ZWD' => "Z$",
        };
    }
}
